export const subjects = [
    { id: "bel_lang", name: "Бел. яз." },
    { id: "bel_lit", name: "Бел. лит." },
    { id: "rus_lang", name: "Русск. яз." },
    { id: "rus_lit", name: "Русск. лит." },
    { id: "foreign_lang", name: "Ин. яз." },
    { id: "math", name: "Математика" },
    { id: "informatics", name: "Информатика" },
    { id: "world_history", name: "Всем. истор." },
    { id: "bel_history", name: "Истор. Бел." },
    { id: "social_studies", name: "Обществов." },
    { id: "geography", name: "География" },
    { id: "biology", name: "Биология" },
    { id: "physics", name: "Физика" },
    { id: "astronomy", name: "Астрономия" },
    { id: "chemistry", name: "Химия" },
    { id: "physical_edu", name: "Физ-ра" },
    { id: "dp_mp", name: "ДП/МП" },
  ]
  